services:
  server:
    build: .
    container_name: os-server
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8081:8081" # TCP Socket (Client.java)
>>>>>>> 00a2f7daee9295e6b2353a752f02b1fae54b38c5
    volumes:
      - ./:/workspace
    restart: unless-stopped
